/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista.Admin;

import com.coderhouse.chapin.market.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author emili_zxg0ruq
 */
public class PanelTarjetas extends javax.swing.JPanel {

    public int idTienda;
    public int idCliente;
    Connection conexion = new Conexion().establecerConexion();

    public PanelTarjetas(int idTienda) {
        this.idTienda = idTienda;
        initComponents();
        txtTarjeta.addItem("comun");
        txtTarjeta.addItem("oro");
        txtTarjeta.addItem("platino");
        txtTarjeta.addItem("diamante");
        txtTarjeta.addItem("ninguna");
    }

    private int getTarjeta(String tarjeta) {

        if (tarjeta.equals("comun")) {
            return 0;
        }
        if (tarjeta.equals("oro")) {
            return 1;
        }
        if (tarjeta.equals("platino")) {
            return 2;
        }
        if (tarjeta.equals("diamante")) {
            return 3;
        }
        if (tarjeta.equals("ninguna")) {
            return 4;
        }
        return 0;
    }

    /**
     * Creates new form PanelTarjetas
     */
    public PanelTarjetas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        txtbuscador = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNit = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtPuntos = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btbuscar = new javax.swing.JLabel();
        btnIngresarCliente = new javax.swing.JLabel();
        txtTarjeta = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtDescuento = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(910, 680));
        setMinimumSize(new java.awt.Dimension(910, 680));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("BUSCAR CLIENTE POR NIT");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        txtbuscador.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtbuscador.setToolTipText("");
        txtbuscador.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        txtbuscador.setOpaque(true);
        txtbuscador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscadorActionPerformed(evt);
            }
        });
        add(txtbuscador, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 320, 30));

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("NIT:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 40, -1));

        txtNit.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtNit.setToolTipText("");
        txtNit.setBorder(null);
        txtNit.setOpaque(true);
        txtNit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNitActionPerformed(evt);
            }
        });
        add(txtNit, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 100, 33));

        jLabel3.setText("_____________");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 110, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 1020, 10));

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("NOMBRE:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, -1, -1));

        txtNombre.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtNombre.setToolTipText("");
        txtNombre.setBorder(null);
        txtNombre.setOpaque(true);
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 190, 33));

        jLabel8.setText("___________________________");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 260, -1));

        jLabel11.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("PUNTOS:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, -1, -1));

        txtPuntos.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtPuntos.setToolTipText("");
        txtPuntos.setBorder(null);
        txtPuntos.setOpaque(true);
        txtPuntos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPuntosActionPerformed(evt);
            }
        });
        add(txtPuntos, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 100, 33));

        jLabel12.setText("_____________");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 110, -1));

        jLabel18.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 102, 102));
        jLabel18.setText("TARJETA:");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, -1, -1));

        btbuscar.setBackground(new java.awt.Color(17, 105, 142));
        btbuscar.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btbuscar.setForeground(new java.awt.Color(255, 255, 255));
        btbuscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btbuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btbuscar.setMaximumSize(new java.awt.Dimension(50, 50));
        btbuscar.setMinimumSize(new java.awt.Dimension(50, 50));
        btbuscar.setOpaque(true);
        btbuscar.setPreferredSize(new java.awt.Dimension(50, 50));
        btbuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btbuscarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btbuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btbuscarMouseExited(evt);
            }
        });
        add(btbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 40, 30));

        btnIngresarCliente.setBackground(new java.awt.Color(17, 105, 142));
        btnIngresarCliente.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnIngresarCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresarCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnIngresarCliente.setText("MODIFICAR");
        btnIngresarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIngresarCliente.setOpaque(true);
        btnIngresarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIngresarClienteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnIngresarClienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnIngresarClienteMouseExited(evt);
            }
        });
        add(btnIngresarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 500, 170, 40));

        txtTarjeta.setEditable(true);
        txtTarjeta.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtTarjeta.setToolTipText("");
        txtTarjeta.setBorder(null);
        txtTarjeta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtTarjeta.setDoubleBuffered(true);
        txtTarjeta.setFocusable(false);
        txtTarjeta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTarjetaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtTarjetaMouseEntered(evt);
            }
        });
        txtTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTarjetaActionPerformed(evt);
            }
        });
        txtTarjeta.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtTarjetaPropertyChange(evt);
            }
        });
        add(txtTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 390, 270, 30));

        jLabel9.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("DESCUENTO");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, -1, -1));

        txtDescuento.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtDescuento.setToolTipText("");
        txtDescuento.setBorder(null);
        txtDescuento.setOpaque(true);
        txtDescuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescuentoActionPerformed(evt);
            }
        });
        add(txtDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, 190, 33));

        jLabel10.setText("___________________________");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 310, 260, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtbuscadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscadorActionPerformed

    private void txtNitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNitActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtPuntosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPuntosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPuntosActionPerformed

    private void btbuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btbuscarMouseClicked
        // TODO add your handling code here:
        // Obtén el NIT ingresado por el usuario desde el campo de texto txtbuscador
        String nitCliente = txtbuscador.getText().trim();

        // Verifica que el NIT no esté vacío
        if (!nitCliente.isEmpty()) {
            // Realiza una consulta SQL para buscar al cliente por NIT
            String consulta = "SELECT idCliente, nombreCliente, telefono, dpi, tarjeta, puntos, descuento, direccion "
                    + "FROM ControlPersonal.Cliente WHERE nitCliente = ?";

            Connection conexion = new Conexion().establecerConexion();

            try {
                PreparedStatement pstmt = conexion.prepareStatement(consulta);
                pstmt.setString(1, nitCliente); // Asigna el valor del NIT a la consulta
                ResultSet resultado = pstmt.executeQuery();

                boolean clienteEncontrado = false; // Variable para indicar si se encontró un cliente

                while (resultado.next()) {
                    idCliente = resultado.getInt("idCliente");
                    String nombre = resultado.getString("nombreCliente");
                    String telefono = resultado.getString("telefono");
                    String dpi = resultado.getString("dpi");
                    String tarjeta = resultado.getString("tarjeta");
                    int puntos = resultado.getInt("puntos");
                    double descuento = resultado.getDouble("descuento");
                    String direccion = resultado.getString("direccion");

                    // Establece los atributos del cliente en los campos de texto
                    txtNit.setText(nitCliente);
                    txtNombre.setText(nombre);
                    txtDescuento.setText(String.valueOf(descuento));
                    txtPuntos.setText(String.valueOf(puntos));
                    txtTarjeta.setSelectedIndex(getTarjeta(tarjeta));

                    clienteEncontrado = true; // Se encontró al menos un cliente
                }

                resultado.close();
                pstmt.close();
                conexion.close();

                if (!clienteEncontrado) {
                    JOptionPane.showMessageDialog(this, "Cliente no encontrado.");
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Error al buscar el cliente: " + e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Ingrese un NIT válido para buscar al cliente.");
        }
    }//GEN-LAST:event_btbuscarMouseClicked

    private void btbuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btbuscarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btbuscarMouseEntered

    private void btbuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btbuscarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btbuscarMouseExited

    private void btnIngresarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarClienteMouseClicked
        try {
            // TODO add your handling code here:
            
            // Las credenciales del administrador son correctas, procede con la actualización del cliente
            String sql = "UPDATE ControlPersonal.Cliente SET   tarjeta=?, puntos=?, descuento=? WHERE idCliente =?";
            
            PreparedStatement pst = conexion.prepareStatement(sql);
            
            pst.setString(1, txtTarjeta.getSelectedItem().toString());
            pst.setInt(2, Integer.parseInt(txtPuntos.getText()));
            pst.setFloat(3, Float.parseFloat(txtDescuento.getText()));
            pst.setInt(4, idCliente);
            
            int rowsInserted = pst.executeUpdate();
            if (rowsInserted > 0) {
                JOptionPane.showMessageDialog(this, "La actualizacion se  realizó correctamente.");
                //System.out.println("La actualización se realizó correctamente.");
            }
        } catch (SQLException ex) {
            Logger.getLogger(PanelTarjetas.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnIngresarClienteMouseClicked

    private void btnIngresarClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarClienteMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIngresarClienteMouseEntered

    private void btnIngresarClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarClienteMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIngresarClienteMouseExited

    private void txtTarjetaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTarjetaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTarjetaMouseClicked

    private void txtTarjetaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTarjetaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTarjetaMouseEntered

    private void txtTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTarjetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTarjetaActionPerformed

    private void txtTarjetaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtTarjetaPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTarjetaPropertyChange

    private void txtDescuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescuentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescuentoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btbuscar;
    private javax.swing.JLabel btnIngresarCliente;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtDescuento;
    private javax.swing.JTextField txtNit;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPuntos;
    private javax.swing.JComboBox<String> txtTarjeta;
    private javax.swing.JTextField txtbuscador;
    // End of variables declaration//GEN-END:variables
}
