/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista.Admin;

import com.coderhouse.chapin.market.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author emili_zxg0ruq
 */
public class TopProductos extends javax.swing.JPanel {

    public int idTienda;
    private DefaultTableModel tableModel;
    Connection conexion = new Conexion().establecerConexion();

    //jTableProducto
    public TopProductos(int idTienda) throws SQLException {
        this.idTienda = idTienda;
        initComponents();
        tableModel = new DefaultTableModel();
        tableModel.addColumn("ID Producto");
        tableModel.addColumn("Cantidad de Ventas");
        mostrar();
        jTableProducto.setModel(tableModel);
    }

    /**
     * Creates new form TopProductos
     */
    public TopProductos() {
        initComponents();
    
    }

    public void mostrar() throws SQLException {

        String sql = "SELECT idProducto, COUNT(*) AS cantidadVentas "
                + "FROM ControlVentas.DetalleVenta "
                + "GROUP BY idProducto "
                + "ORDER BY cantidadVentas DESC "
                + "LIMIT 10";

        try (PreparedStatement pst = conexion.prepareStatement(sql)) {
            try (ResultSet resultado = pst.executeQuery()) {
                while (resultado.next()) {
                    // Procesa los resultados
                    int idProducto = resultado.getInt("idProducto");
                    int cantidadVentas = resultado.getInt("cantidadVentas");
                    System.out.println("ID Producto: " + idProducto + ", Cantidad de Ventas: " + cantidadVentas);
                    Object[] fila = {idProducto, cantidadVentas};
                    tableModel.addRow(fila);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProducto = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(910, 680));
        setMinimumSize(new java.awt.Dimension(910, 680));
        setPreferredSize(new java.awt.Dimension(910, 680));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(22, 199, 154));
        jLabel3.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("TOP 10 PRODUCTOS");
        jLabel3.setOpaque(true);
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 440, 50));

        jTableProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableProducto);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProducto;
    // End of variables declaration//GEN-END:variables
}
