/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista.Admin;

import com.coderhouse.chapin.market.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author emili_zxg0ruq
 */
public class TopTiendas extends javax.swing.JPanel {

    /**
     * Creates new form TopTiendas
     */
    public int idTienda1;
    private DefaultTableModel tableModel;
    Connection conexion = new Conexion().establecerConexion();

    public TopTiendas(int idTienda) throws SQLException {
        this.idTienda1 = idTienda;
        initComponents();
        tableModel = new DefaultTableModel();
        tableModel.addColumn("Nombre Tienda");
        tableModel.addColumn("Total Venta");

        // Asigna el modelo de tabla a la jTableHistorial
        jTableSucursales.setModel(tableModel);
        mostrar();

    }

    public TopTiendas() {
        initComponents();

        tableModel = new DefaultTableModel();
        tableModel.addColumn("Nombre Tienda");
        tableModel.addColumn("Total Venta");

        // Asigna el modelo de tabla a la jTableHistorial
        jTableSucursales.setModel(tableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private String obtenerNombreTienda(int id) {
        Connection conexion = new Conexion().establecerConexion();
        String nombreTienda = "";

        try {
            String consultaTienda = "SELECT nombreTienda FROM ControlEmpresas.Tienda WHERE idTienda = ?";
            PreparedStatement pstmtTienda = conexion.prepareStatement(consultaTienda);
            pstmtTienda.setInt(1, id);
            ResultSet resultadoTienda = pstmtTienda.executeQuery();

            if (resultadoTienda.next()) {
                nombreTienda = resultadoTienda.getString("nombreTienda");
            }

            resultadoTienda.close();
            pstmtTienda.close();
            conexion.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al consultar la tienda: " + e.getMessage());
        }

        return nombreTienda;
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSucursales = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(910, 680));
        setMinimumSize(new java.awt.Dimension(910, 680));
        setPreferredSize(new java.awt.Dimension(910, 680));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(22, 199, 154));
        jLabel3.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("TOP 3 SUCURSALES ");
        jLabel3.setOpaque(true);
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 440, 50));

        jTableSucursales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableSucursales);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, -1, -1));
    }// </editor-fold>//GEN-END:initComponents
public void mostrar() throws SQLException {
        String sql = "SELECT idTienda, SUM(total) AS totalVentas "
                + "FROM ControlVentas.Venta "
                + "GROUP BY idTienda "
                + "ORDER BY totalVentas DESC "
                + "LIMIT 3";

        try (PreparedStatement pst = conexion.prepareStatement(sql)) {
            try (ResultSet resultado = pst.executeQuery()) {
                while (resultado.next()) {
                    // Procesa los resultados
                    int idTienda2 = resultado.getInt("idTienda");
                    double totalVentas = resultado.getDouble("totalVentas");
                    String nombreTienda = (obtenerNombreTienda(idTienda2));
                    Object[] fila = {nombreTienda, totalVentas};
                    tableModel.addRow(fila);
                    System.out.println("NOMBRE : " + nombreTienda
                            + ", Total Ventas: " + totalVentas);
                }
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableSucursales;
    // End of variables declaration//GEN-END:variables
}
