/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista.Cajero;

import Modelo.Producto;
import Vista.Inventario.trasladarProducto;
import com.coderhouse.chapin.market.Conexion;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author emili_zxg0ruq
 */
public class PanelVenta extends javax.swing.JPanel {

    /**
     * Creates new form PanelVenta
     */
    public int id;
    private List<Producto> productosDisponibles; // Lista de productos disponibles
    private List<Producto> productosEnVenta; // Lista de productos en la venta actual
    Connection conexion = new Conexion().establecerConexion();

    public PanelVenta(int id) {
        this.id = id;
        initComponents();
        agregarDatosSelect();

    }
    // Método para cargar la lista de productos disponibles en la tienda

    // Método para actualizar el combo box de productos disponibles
    public void agregarDatosSelect() {

        String sql = "SELECT nombreProducto FROM ControlEmpresas.Producto WHERE idTienda = ? AND estado = false AND cantidad > 0";
        PreparedStatement pst;
        try {
            pst = conexion.prepareStatement(sql);
            pst.setInt(1, id);
            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                String nombreProducto = rs.getString("nombreProducto");
                System.out.println("nom " + nombreProducto);
                jProducto.addItem(nombreProducto);
            }
        } catch (SQLException ex) {
            Logger.getLogger(trasladarProducto.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public int obtenerItem() {
        String sql = "SELECT idProducto FROM ControlEmpresas.Producto WHERE idTienda = ? AND nombreProducto = ?";
        PreparedStatement pst;
        try {
            pst = conexion.prepareStatement(sql);
            pst.setInt(1, id);
            pst.setString(2, jProducto.getSelectedItem().toString());
            ResultSet rs = pst.executeQuery();

            // Mueve el cursor al primer registro (si existe)
            if (rs.next()) {
                int aux = rs.getInt("idProducto");
                return aux;
            } else {
                return 0;
            }
        } catch (SQLException ex) {
            Logger.getLogger(trasladarProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
        return 0;
    }

    public boolean cantidadDisponible() {
        String sql = "SELECT cantidad FROM ControlEmpresas.Producto WHERE idTienda = ? AND idProducto = ?";
        PreparedStatement pst;
        try {
            pst = conexion.prepareStatement(sql);
            pst.setInt(1, id);
            pst.setInt(2, obtenerItem());
            ResultSet rs = pst.executeQuery();
            // Mueve el cursor al primer registro (si existe)
            if (rs.next()) {
                int aux = rs.getInt("cantidad");
                System.out.println("AUX " + aux);
                int cantidadSeleccionada = (int) jCantidadProd.getValue();
                System.out.println("select " + cantidadSeleccionada);
                if (aux > cantidadSeleccionada) {
                    return false;
                } else {

                    return true;
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(trasladarProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        txtbuscador = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNit = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtPuntos = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtTarjeta = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        lbTotal = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        jCantidadProd = new javax.swing.JSpinner();
        jLabel19 = new javax.swing.JLabel();
        jProducto = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        btnIngresarProd = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator4 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProductos = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lbDescuento = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        btnConfirmarDescuento = new javax.swing.JLabel();
        btbuscar = new javax.swing.JLabel();
        btnIngresarCliente = new javax.swing.JLabel();
        btnConfirmar = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1500, 710));
        setMinimumSize(new java.awt.Dimension(1500, 710));
        setPreferredSize(new java.awt.Dimension(1500, 710));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("BUSCAR CLIENTE POR NIT");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        txtbuscador.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtbuscador.setToolTipText("");
        txtbuscador.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        txtbuscador.setOpaque(true);
        txtbuscador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscadorActionPerformed(evt);
            }
        });
        add(txtbuscador, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 320, 30));

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("NIT:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 40, -1));

        txtNit.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtNit.setToolTipText("");
        txtNit.setBorder(null);
        txtNit.setOpaque(true);
        txtNit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNitActionPerformed(evt);
            }
        });
        add(txtNit, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 100, 33));

        jLabel3.setText("_____________");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 110, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 1020, 10));

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("NOMBRE:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, -1, -1));

        txtNombre.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtNombre.setToolTipText("");
        txtNombre.setBorder(null);
        txtNombre.setOpaque(true);
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 260, 33));

        jLabel8.setText("___________________________");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 260, -1));

        jLabel9.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("TELÉFONO:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, -1, -1));

        txtTelefono.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtTelefono.setToolTipText("");
        txtTelefono.setBorder(null);
        txtTelefono.setOpaque(true);
        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });
        add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, 120, 33));

        jLabel10.setText("________________________");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 170, 120, -1));

        jLabel11.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("PUNTOS:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

        txtPuntos.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtPuntos.setToolTipText("");
        txtPuntos.setBorder(null);
        txtPuntos.setOpaque(true);
        txtPuntos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPuntosActionPerformed(evt);
            }
        });
        add(txtPuntos, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 100, 33));

        jLabel12.setText("_____________");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 110, -1));

        txtTarjeta.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtTarjeta.setToolTipText("");
        txtTarjeta.setBorder(null);
        txtTarjeta.setOpaque(true);
        txtTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTarjetaActionPerformed(evt);
            }
        });
        add(txtTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 250, 33));

        jLabel14.setText("___________________________");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 270, -1));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 1020, 10));

        jLabel15.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("TOTAL");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 630, -1, -1));

        lbTotal.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lbTotal.setToolTipText("");
        lbTotal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        lbTotal.setOpaque(true);
        lbTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbTotalActionPerformed(evt);
            }
        });
        add(lbTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 650, 120, 33));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(22, 199, 154), 1, true));

        jCantidadProd.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jCantidadProd.setBorder(null);

        jLabel19.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(102, 102, 102));
        jLabel19.setText("Cantidad");

        jProducto.setEditable(true);
        jProducto.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jProducto.setToolTipText("");
        jProducto.setBorder(null);
        jProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jProducto.setDoubleBuffered(true);
        jProducto.setFocusable(false);
        jProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jProductoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jProductoMouseEntered(evt);
            }
        });
        jProducto.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jProductoPropertyChange(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(102, 102, 102));
        jLabel20.setText("Producto");

        btnIngresarProd.setBackground(new java.awt.Color(17, 105, 142));
        btnIngresarProd.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnIngresarProd.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresarProd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnIngresarProd.setText("CONFIRMAR");
        btnIngresarProd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIngresarProd.setOpaque(true);
        btnIngresarProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIngresarProdMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnIngresarProdMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnIngresarProdMouseExited(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(102, 102, 102));
        jLabel23.setText(" AGREGAR PRODCUTOS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel19)
                                    .addComponent(jCantidadProd, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel23)))
                        .addGap(0, 26, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(btnIngresarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel19)
                .addGap(8, 8, 8)
                .addComponent(jCantidadProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnIngresarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 370, 290));

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("DIRECCIÓN:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 130, -1, -1));

        txtDireccion.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtDireccion.setToolTipText("");
        txtDireccion.setBorder(null);
        txtDireccion.setOpaque(true);
        add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 150, 220, 33));

        jLabel2.setText("_________________________________________");
        jLabel2.setToolTipText("");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 170, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(22, 199, 154), 1, true));

        jTableProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableProductos);

        jLabel13.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("  PRODCUTOS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator4)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, 590, 290));

        jLabel18.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 102, 102));
        jLabel18.setText("TARJETA:");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, -1, -1));

        lbDescuento.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lbDescuento.setToolTipText("");
        lbDescuento.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        lbDescuento.setOpaque(true);
        lbDescuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbDescuentoActionPerformed(evt);
            }
        });
        add(lbDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 650, 120, 33));

        jLabel21.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(102, 102, 102));
        jLabel21.setText("TOTAL CON DESCUENTO");
        add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 630, -1, -1));

        btnConfirmarDescuento.setBackground(new java.awt.Color(22, 199, 154));
        btnConfirmarDescuento.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnConfirmarDescuento.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmarDescuento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnConfirmarDescuento.setText("APLICAR DESCUENTO");
        btnConfirmarDescuento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConfirmarDescuento.setOpaque(true);
        btnConfirmarDescuento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConfirmarDescuentoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnConfirmarDescuentoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnConfirmarDescuentoMouseExited(evt);
            }
        });
        add(btnConfirmarDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 640, 220, 40));

        btbuscar.setBackground(new java.awt.Color(17, 105, 142));
        btbuscar.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btbuscar.setForeground(new java.awt.Color(255, 255, 255));
        btbuscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btbuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btbuscar.setMaximumSize(new java.awt.Dimension(50, 50));
        btbuscar.setMinimumSize(new java.awt.Dimension(50, 50));
        btbuscar.setOpaque(true);
        btbuscar.setPreferredSize(new java.awt.Dimension(50, 50));
        btbuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btbuscarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btbuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btbuscarMouseExited(evt);
            }
        });
        add(btbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 40, 30));

        btnIngresarCliente.setBackground(new java.awt.Color(17, 105, 142));
        btnIngresarCliente.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnIngresarCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresarCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnIngresarCliente.setText("Ingresar");
        btnIngresarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIngresarCliente.setOpaque(true);
        btnIngresarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIngresarClienteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnIngresarClienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnIngresarClienteMouseExited(evt);
            }
        });
        add(btnIngresarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 230, 150, 40));

        btnConfirmar.setBackground(new java.awt.Color(25, 69, 107));
        btnConfirmar.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnConfirmar.setText("CONFIRMAR VENTA");
        btnConfirmar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConfirmar.setOpaque(true);
        btnConfirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConfirmarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnConfirmarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnConfirmarMouseExited(evt);
            }
        });
        add(btnConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 640, 220, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void txtNitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNitActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void txtPuntosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPuntosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPuntosActionPerformed

    private void txtTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTarjetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTarjetaActionPerformed

    private void lbTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbTotalActionPerformed

    private void jProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jProductoMouseClicked
        // TODO add your handling code here:
        //noti.setBackground(Color.white);
    }//GEN-LAST:event_jProductoMouseClicked

    private void jProductoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jProductoMouseEntered
        // TODO add your handling code here:
        //noti.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_jProductoMouseEntered

    private void jProductoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jProductoPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jProductoPropertyChange

    private void btnIngresarProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarProdMouseClicked
        // TODO add your handling code here:
        ////aquiiii
        if (cantidadDisponible() == true) {
            System.out.println("disponible");
        } else {
            System.out.println("No disponible");
        }
    }//GEN-LAST:event_btnIngresarProdMouseClicked

    private void btnIngresarProdMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarProdMouseEntered
        // TODO add your handling code here:
        btnIngresarProd.setBackground(new Color(22, 199, 154));
    }//GEN-LAST:event_btnIngresarProdMouseEntered

    private void btnIngresarProdMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarProdMouseExited
        // TODO add your handling code here:
        btnIngresarProd.setBackground(new Color(25, 69, 107));
    }//GEN-LAST:event_btnIngresarProdMouseExited

    private void lbDescuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbDescuentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbDescuentoActionPerformed

    private void btnConfirmarDescuentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmarDescuentoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConfirmarDescuentoMouseClicked

    private void btnConfirmarDescuentoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmarDescuentoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConfirmarDescuentoMouseEntered

    private void btnConfirmarDescuentoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmarDescuentoMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConfirmarDescuentoMouseExited

    private void txtbuscadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscadorActionPerformed

    private void btbuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btbuscarMouseClicked
        // TODO add your handling code here:
        // Obtén el NIT ingresado por el usuario desde el campo de texto txtbuscador
        String nitCliente = txtbuscador.getText().trim();

        // Verifica que el NIT no esté vacío
        if (!nitCliente.isEmpty()) {
            // Realiza una consulta SQL para buscar al cliente por NIT
            String consulta = "SELECT nombreCliente, telefono, dpi, tarjeta, puntos, descuento, direccion "
                    + "FROM ControlPersonal.Cliente WHERE nitCliente = ?";

            Connection conexion = new Conexion().establecerConexion();

            try {
                PreparedStatement pstmt = conexion.prepareStatement(consulta);
                pstmt.setString(1, nitCliente); // Asigna el valor del NIT a la consulta
                ResultSet resultado = pstmt.executeQuery();

                boolean clienteEncontrado = false; // Variable para indicar si se encontró un cliente

                while (resultado.next()) {
                    String nombre = resultado.getString("nombreCliente");
                    String telefono = resultado.getString("telefono");
                    String dpi = resultado.getString("dpi");
                    String tarjeta = resultado.getString("tarjeta");
                    int puntos = resultado.getInt("puntos");
                    double descuento = resultado.getDouble("descuento");
                    String direccion = resultado.getString("direccion");

                    // Establece los atributos del cliente en los campos de texto
                    txtNit.setText(nitCliente);
                    txtNombre.setText(nombre);
                    txtTelefono.setText(telefono);
                    txtPuntos.setText(String.valueOf(puntos));
                    txtTarjeta.setText(tarjeta);
                    txtDireccion.setText(direccion);

                    clienteEncontrado = true; // Se encontró al menos un cliente
                }

                resultado.close();
                pstmt.close();
                conexion.close();

                if (!clienteEncontrado) {
                    JOptionPane.showMessageDialog(this, "Cliente no encontrado.");
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Error al buscar el cliente: " + e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Ingrese un NIT válido para buscar al cliente.");
        }
    }//GEN-LAST:event_btbuscarMouseClicked

    private void btbuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btbuscarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btbuscarMouseEntered

    private void btbuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btbuscarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btbuscarMouseExited

    private void btnIngresarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarClienteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIngresarClienteMouseClicked

    private void btnIngresarClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarClienteMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIngresarClienteMouseEntered

    private void btnIngresarClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarClienteMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIngresarClienteMouseExited

    private void btnConfirmarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConfirmarMouseClicked

    private void btnConfirmarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConfirmarMouseEntered

    private void btnConfirmarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConfirmarMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btbuscar;
    private javax.swing.JLabel btnConfirmar;
    private javax.swing.JLabel btnConfirmarDescuento;
    private javax.swing.JLabel btnIngresarCliente;
    private javax.swing.JLabel btnIngresarProd;
    private javax.swing.JSpinner jCantidadProd;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> jProducto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable jTableProductos;
    private javax.swing.JTextField lbDescuento;
    private javax.swing.JTextField lbTotal;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNit;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPuntos;
    private javax.swing.JTextField txtTarjeta;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtbuscador;
    // End of variables declaration//GEN-END:variables
}
