/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista.Inventario;

import com.coderhouse.chapin.market.Conexion;
import java.awt.Color;
import java.sql.PreparedStatement;
import javax.swing.*;
import javax.swing.plaf.basic.BasicComboBoxUI;
import java.awt.Graphics;
import java.awt.event.ItemEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.awt.event.ItemListener;
import static java.lang.Thread.sleep;

/**
 *
 * @author emili_zxg0ruq
 */
public class trasladarProducto extends javax.swing.JPanel {

    /**
     * Creates new form trasladarProducto
     */
    public trasladarProducto(int id) {
        initComponents();
        this.id = id;
        agregarDatosSelect();
    }

    public int id;
    Connection conexion = new Conexion().establecerConexion();
    int test;

    public trasladarProducto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jCantidad = new javax.swing.JSpinner();
        btnIngresar = new javax.swing.JLabel();
        jOpciones = new javax.swing.JComboBox<>();
        noti = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(910, 680));
        setMinimumSize(new java.awt.Dimension(910, 680));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(22, 199, 154));
        jLabel3.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText(" TRASLADAR PRODUCTO DE BODEGA A ESTANTERÍA");
        jLabel3.setOpaque(true);
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 650, 50));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Producto");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, -1, -1));

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Pasillo");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, -1, -1));

        jCantidad.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jCantidad.setBorder(null);
        jPanel2.add(jCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 80, -1));

        btnIngresar.setBackground(new java.awt.Color(25, 69, 107));
        btnIngresar.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnIngresar.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnIngresar.setText("CONFIRMAR");
        btnIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIngresar.setOpaque(true);
        btnIngresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIngresarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnIngresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnIngresarMouseExited(evt);
            }
        });
        jPanel2.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 390, 150, 40));

        jOpciones.setEditable(true);
        jOpciones.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jOpciones.setToolTipText("");
        jOpciones.setBorder(null);
        jOpciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jOpciones.setDoubleBuffered(true);
        jOpciones.setFocusable(false);
        jOpciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jOpcionesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jOpcionesMouseEntered(evt);
            }
        });
        jOpciones.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jOpcionesPropertyChange(evt);
            }
        });
        jPanel2.add(jOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 300, 30));

        noti.setBackground(new java.awt.Color(255, 255, 255));
        noti.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        noti.setForeground(new java.awt.Color(255, 255, 255));
        noti.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        noti.setText("jLabel1");
        noti.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        noti.setOpaque(true);
        jPanel2.add(noti, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 510, 320, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(69, 69, 69))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(26, 26, 26))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void agregarDatosSelect() {

        String sql = "SELECT nombreProducto FROM ControlEmpresas.Producto WHERE idTienda = ? AND estado = true";
        PreparedStatement pst;
        try {
            pst = conexion.prepareStatement(sql);
            pst.setInt(1, id);
            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                String nombreProducto = rs.getString("nombreProducto");
                jOpciones.addItem(nombreProducto);
            }
        } catch (SQLException ex) {
            Logger.getLogger(trasladarProducto.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public int obtenerItem() {
        String sql = "SELECT idProducto FROM ControlEmpresas.Producto WHERE idTienda = ? AND nombreProducto = ?";
        PreparedStatement pst;
        try {
            pst = conexion.prepareStatement(sql);
            pst.setInt(1, id);
            pst.setString(2, jOpciones.getSelectedItem().toString());
            ResultSet rs = pst.executeQuery();

            // Mueve el cursor al primer registro (si existe)
            if (rs.next()) {
                int aux = rs.getInt("idProducto");
                return aux;
            } else {
                return 0;
            }
        } catch (SQLException ex) {
            Logger.getLogger(trasladarProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
        return 0;
    }
    private void btnIngresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarMouseClicked
        // TODO add your handling code here:
        // INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda)
        //VALUES (p_nombreProducto, p_fabricante, p_precio, p_cantidad, p_estado, p_pasillo, p_idTienda);
        // TODO add your handling code here:
        try {

            String sql = "UPDATE ControlEmpresas.Producto SET estado = false, pasillo = ? WHERE idProducto = ?";
            PreparedStatement pst = conexion.prepareStatement(sql);
            int cantidadSeleccionada = (int) jCantidad.getValue();
            pst.setInt(1, cantidadSeleccionada);
            pst.setInt(2, obtenerItem());

            int filasAfectadas = pst.executeUpdate();

            if (filasAfectadas > 0) {
                System.out.println("Producto modificado correctamente.");
                noti.setBackground(new Color(121, 172, 120));
                noti.setText("Producto Trasladado");

                sleep(10);
            } else {
                System.out.println("No se encontró ningún producto con el ID proporcionado.");
            }
        } catch (SQLException e) {
            e.printStackTrace();
        } catch (InterruptedException ex) {
            Logger.getLogger(trasladarProducto.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnIngresarMouseClicked

    private void btnIngresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarMouseEntered
        // TODO add your handling code here:
        btnIngresar.setBackground(new Color(22, 199, 154));
    }//GEN-LAST:event_btnIngresarMouseEntered

    private void btnIngresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarMouseExited
        // TODO add your handling code here:
        btnIngresar.setBackground(new Color(25, 69, 107));
    }//GEN-LAST:event_btnIngresarMouseExited

    private void jOpcionesPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jOpcionesPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jOpcionesPropertyChange

    private void jOpcionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jOpcionesMouseClicked
        // TODO add your handling code here:
        noti.setBackground(Color.white);
    }//GEN-LAST:event_jOpcionesMouseClicked

    private void jOpcionesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jOpcionesMouseEntered
        // TODO add your handling code here:
        noti.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_jOpcionesMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnIngresar;
    private javax.swing.JSpinner jCantidad;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JComboBox<String> jOpciones;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel noti;
    // End of variables declaration//GEN-END:variables
}
