                                            /*-----SUCURSALES-----*/

INSERT INTO ControlEmpresas.Tienda(nombreTienda, direccion, telefono) VALUES ('Sucursal Centro', 'Zona 12 Quetzaltenango', '77580912');
INSERT INTO ControlEmpresas.Tienda(nombreTienda, direccion, telefono) VALUES ('Sucursal Norte', 'Zona 1 Guatemala', '78908765');
INSERT INTO ControlEmpresas.Tienda(nombreTienda, direccion, telefono) VALUES ('Sucursal Sur', 'Zona 3 San Marcos', '79086543');

                                            /*-----PRODUCTOS-----*/

/*SUCURSAL 1 100 productos diferentes*/
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Coca-Cola', 'Coca-Cola', 10, 100, False, 1, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Pepsi', 'Pepsi', 10, 100, False, 1, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Fanta', 'Coca-Cola', 10, 100, False, 1, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Sprite', 'Coca-Cola', 10, 100, False, 1, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('7up', 'Pepsi', 10, 100, False, 1, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Fresca', 'Coca-Cola', 10, 100, False, 1, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Mirinda', 'Pepsi', 10, 100, False, 1, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Coca-Cola Light', 'Coca-Cola', 10, 100, False, 1, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Pepsi Light', 'Pepsi', 10, 100, False, 1, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Fanta Light', 'Coca-Cola', 10, 100, False, 1, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Lays', 'Sabritas', 5, 100, False, 1, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Doritos', 'Sabritas', 5, 100, False, 1, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Ruffles', 'Sabritas', 5, 100, False, 1, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Cheetos', 'Sabritas', 5, 100, False, 1, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Tostitos', 'Sabritas', 5, 100, False, 1, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Rancheritos', 'Sabritas', 5, 100, False, 1, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Churrumais', 'Sabritas', 5, 100, False, 1, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Chetos Bolita', 'Sabritas', 5, 100, False, 1, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Chetos Poff', 'Sabritas', 5, 100, False, 1, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Chetos Torciditos', 'Sabritas', 5, 100, False, 1, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Chetos Flamin Hot', 'Sabritas', 5, 100, False, 1, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Chetos Bolita Flamin Hot', 'Sabritas', 5, 100, False, 1, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Arroz', 'Gallo dorado', 15, 100, False, 2, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Frijol', 'Gallo dorado', 15, 100, False, 2, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Azucar', 'Gallo dorado', 15, 100, False, 2, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Sal', 'Cristal Sal', 15, 100, False, 2, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Aceite', 'Mirasol', 15, 100, False, 2, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Cafe', 'Nescafe', 15, 100, False, 2, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Maseca', 'Maseca', 15, 100, False, 2, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Harina', 'Maseca', 15, 100, False, 2, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Cereal Zucaritas', 'Zucaritas', 15, 100, False, 2, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Cereal Choco Krispis', 'Choco Krispis', 15, 100, False, 2, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Cereal Corn Flakes', 'Corn Flakes', 15, 100, False, 2, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Cereal Choco Flakes', 'Choco Flakes', 15, 100, False, 2, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Leche', 'Dos Pinos', 12, 100, False, 3, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Leche', 'Alpura', 12, 100, False, 3, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Leche', 'Pil', 12, 100, False, 3, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Leche', 'Lala', 12, 100, False, 3, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Jugo', 'Ideal', 5, 100, False, 3, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Jugo', 'Del Valle', 5, 100, False, 3, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Jugo', 'Jumex', 5, 100, False, 3, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Jugo', 'Jugos del Valle', 5, 100, False, 3, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Salchichas', 'Chimex', 20, 100, False, 3, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Salchichas', 'Chorizo', 20, 100, False, 3, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Jamon', 'Chimex', 20, 100, False, 3, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Queso', 'Lala', 15, 100, False, 3, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Queso', 'Dos Pinos', 15, 100, False, 3, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Queso', 'Pil', 15, 100, False, 3, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Jabon', 'pilas', 15, 100, False, 4, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Jabon', 'Dove', 15, 100, False, 4, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Jabon', 'Palmolive', 15, 100, False, 4, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Shampoo', 'Sedal', 15, 100, False, 4, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Shampoo', 'Pantene', 15, 100, False, 4, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Shampoo', 'Head & Shoulders', 15, 100, True, 4, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Shampoo', 'Dove', 15, 100, True, 4, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Crema', 'Nivea', 15, 100, True, 4, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Crema', 'Ponds', 15, 100, True, 4, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Crema', 'Dove', 15, 100, True, 4, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Crema', 'Palmolive', 15, 100, True, 4, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Papel Higienico', 'Scott', 15, 100, True, 5, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Papel Higienico', 'Suavel', 15, 100, True, 5, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Papel Higienico', 'Elite', 15, 100, True, 5, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Papel Higienico', 'Delsey', 15, 100, True, 5, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Papel Higienico', 'Presto', 15, 100, True, 5, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Video Juego', 'FIFA', 500, 100, True, 5, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Video Juego', 'Call of Duty', 500, 100, True, 5, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Video Juego', 'GTA V', 500, 100, True, 6, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Video Juego', 'FIFA 20', 500, 100, True, 6, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Video Juego', 'Call of Duty Modern Warfare', 500, 100, True, 6, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Desodorante', 'Old Spice', 30, 100, False, 6, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Desodorante', 'Axe', 30, 100, False, 6, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Desodorante', 'Speed Stick', 30, 100, False, 6, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Desodorante', 'Rexona', 30, 100, False, 6, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Desodorante', 'Dove', 30, 100, False, 6, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Desodorante', 'Nivea', 30, 100, False, 6, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Carne', 'exportada', 70, 100, False, 7, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Carne nacional', 'nacional', 70, 100, False, 7, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Carne de res', 'de res', 70, 100, False, 7, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Carne', 'de cerdo', 70, 100, False, 7, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Pollo', 'de pollo', 70, 100, False, 7, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Pavo', 'de pavo', 70, 100, False, 7, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Pescado', 'de pescado', 70, 100, False, 7, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Huevos', 'de gallina', 20, 100, False, 1, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Huevos', 'de codorniz', 20, 100, False, 1, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Agua', 'Salvavidas', 10, 100, False, 1, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Agua', 'Cielo', 10, 100, False, 1, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Agua', 'Dasani', 10, 100, True, 1, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Comida para Perro', 'Chihuahua', 50, 100, True, 1, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Comida para Perro', 'Dog Chow', 50, 100, False, 1, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Comida para Perro', 'Pedigree', 50, 100, True, 1, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Comida para Perro', 'Purina', 50, 100, True, 1, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Salmon', 'De lata', 50, 100, True, 1, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Salmon', 'Fresco', 50, 100, False, 1, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Salmon', 'Ahumado', 50, 100, True, 1, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Atun', 'De lata', 50, 100, False, 1, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Atun', 'Fresco', 50, 100, False, 1, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Dulce', 'Bom Bom', 1, 100, False, 1, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Dulce', 'Chiclets Adams', 1, 100, False, 1, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Dulce', 'Chiclets Trident', 1, 100, False, 1, 1);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Dulce', 'Gomitas', 2, 100, False, 1, 1);

/*SUCURSAL 2 75 productos diferentes*/

INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Coca-Cola', 'Coca-Cola', 10, 100, False, 1, 2);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Pepsi', 'Pepsi', 10, 100, False, 1, 2);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Fanta', 'Coca-Cola', 10, 100, False, 1, 2);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Sprite', 'Coca-Cola', 10, 100, False, 1, 2);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('7up', 'Pepsi', 10, 100, False, 1, 2);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Fresca', 'Coca-Cola', 10, 100, False, 1, 2);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Mirinda', 'Pepsi', 10, 100, False, 1, 2);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Coca-Cola Light', 'Coca-Cola', 10, 100, False, 1, 2);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Pepsi Light', 'Pepsi', 10, 100, False, 1, 2);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Fanta Light', 'Coca-Cola', 10, 100, False, 1, 2);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Lays', 'Sabritas', 5, 100, False, 1, 2);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Doritos', 'Sabritas', 5, 100, False, 1, 2);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Ruffles', 'Sabritas', 5, 100, False, 1, 2);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Cheetos', 'Sabritas', 5, 100, False, 1, 2);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Tostitos', 'Sabritas', 5, 100, False, 1, 2);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Rancheritos', 'Sabritas', 5, 100, False, 1, 2);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Churrumais', 'Sabritas', 5, 100, False, 1, 2);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Carne', 'exportada', 70, 100, False, 7, 2);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Carne nacional', 'nacional', 70, 100, False, 7, 2);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Carne de res', 'de res', 70, 100, False, 7, 2);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Carne', 'de cerdo', 70, 100, False, 7, 2);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Pollo', 'de pollo', 70, 100, False, 7, 2);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Pavo', 'de pavo', 70, 100, False, 7, 2);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Pescado', 'de pescado', 70, 100, False, 7, 2);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Huevos', 'de gallina', 20, 100, False, 1, 2);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Huevos', 'de codorniz', 20, 100, False, 1, 2);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Agua', 'Salvavidas', 10, 100, False, 1, 2);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Agua', 'Cielo', 10, 100, False, 1, 2);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Agua', 'Dasani', 10, 100, True, 1, 2);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Comida para Perro', 'Chihuahua', 50, 100, True, 1, 2);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Comida para Perro', 'Dog Chow', 50, 100, False, 1, 2);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Comida para Perro', 'Pedigree', 50, 100, True, 1, 2);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Comida para Perro', 'Purina', 50, 100, True, 1, 2);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Salmon', 'De lata', 50, 100, True, 1, 2);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Salmon', 'Fresco', 50, 100, False, 1, 2);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Salmon', 'Ahumado', 50, 100, True, 1, 2);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Atun', 'De lata', 50, 100, False, 1, 2);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Atun', 'Fresco', 50, 100, False, 1, 2);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Dulce', 'Bom Bom', 1, 100, False, 1, 2);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Dulce', 'Chiclets Adams', 1, 100, False, 1, 2);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Dulce', 'Chiclets Trident', 1, 100, False, 1, 2);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Dulce', 'Gomitas', 2, 100, False, 1, 2);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Jabon', 'pilas', 15, 100, False, 4, 2);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Jabon', 'Dove', 15, 100, False, 4, 2);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Jabon', 'Palmolive', 15, 100, False, 4, 2);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Shampoo', 'Sedal', 15, 100, False, 4, 2);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Shampoo', 'Pantene', 15, 100, False, 4, 2);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Shampoo', 'Head & Shoulders', 15, 100, True, 4, 2);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Shampoo', 'Dove', 15, 100, True, 4, 2);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Crema', 'Nivea', 15, 100, True, 4, 2);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Crema', 'Ponds', 15, 100, True, 4, 2);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Crema', 'Dove', 15, 100, True, 4, 2);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Crema', 'Palmolive', 15, 100, True, 4, 2);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Papel Higienico', 'Scott', 15, 100, True, 5, 2);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Papel Higienico', 'Suavel', 15, 100, True, 5, 2);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Papel Higienico', 'Elite', 15, 100, True, 5, 2);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Papel Higienico', 'Delsey', 15, 100, True, 5, 2);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Aceite', 'Mirasol', 15, 100, False, 2, 2);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Cafe', 'Nescafe', 15, 100, False, 2, 2);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Maseca', 'Maseca', 15, 100, False, 2, 2);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Harina', 'Maseca', 15, 100, False, 2, 2);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Cereal Zucaritas', 'Zucaritas', 15, 100, False, 2, 2);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Cereal Choco Krispis', 'Choco Krispis', 15, 100, False, 2, 2);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Cereal Corn Flakes', 'Corn Flakes', 15, 100, False, 2, 2);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Cereal Choco Flakes', 'Choco Flakes', 15, 100, False, 2, 2);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Leche', 'Dos Pinos', 12, 100, False, 3, 2);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Leche', 'Alpura', 12, 100, False, 3, 2);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Leche', 'Pil', 12, 100, False, 3, 2);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Leche', 'Lala', 12, 100, False, 3, 2);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Jugo', 'Ideal', 5, 100, False, 3, 2);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Jugo', 'Del Valle', 5, 100, False, 3, 2);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Chetos Bolita', 'Sabritas', 5, 100, False, 1, 2);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Chetos Poff', 'Sabritas', 5, 100, False, 1, 2);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Chetos Torciditos', 'Sabritas', 5, 100, False, 1, 2);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Chetos Flamin Hot', 'Sabritas', 5, 100, False, 1, 2);

/*SUCURSAL 3 75 productos diferentes*/

INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Shampoo', 'Pantene', 15, 100, False, 4, 3);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Shampoo', 'Head & Shoulders', 15, 100, True, 4, 3);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Shampoo', 'Dove', 15, 100, True, 4, 3);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Crema', 'Nivea', 15, 100, True, 4, 3);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Crema', 'Ponds', 15, 100, True, 4, 3);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Crema', 'Dove', 15, 100, True, 4, 3);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Crema', 'Palmolive', 15, 100, True, 4, 3);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Papel Higienico', 'Scott', 15, 100, True, 5, 3);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Papel Higienico', 'Suavel', 15, 100, True, 5, 3);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Papel Higienico', 'Elite', 15, 100, True, 5, 3);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Papel Higienico', 'Delsey', 15, 100, True, 5, 3);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Papel Higienico', 'Presto', 15, 100, True, 5, 3);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Video Juego', 'FIFA', 500, 100, True, 5, 3);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Video Juego', 'Call of Duty', 500, 100, True, 5, 3);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Video Juego', 'GTA V', 500, 100, True, 6, 3);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Video Juego', 'FIFA 20', 500, 100, True, 6, 3);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Video Juego', 'Call of Duty Modern Warfare', 500, 100, True, 6, 3);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Desodorante', 'Old Spice', 30, 100, False, 6, 3);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Desodorante', 'Axe', 30, 100, False, 6, 3);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Desodorante', 'Speed Stick', 30, 100, False, 6, 3);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Desodorante', 'Rexona', 30, 100, False, 6, 3);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Desodorante', 'Dove', 30, 100, False, 6, 3);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Desodorante', 'Nivea', 30, 100, False, 6, 3);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Carne', 'exportada', 70, 100, False, 7, 3);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Carne nacional', 'nacional', 70, 100, False, 7, 3);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Carne de res', 'de res', 70, 100, False, 7, 3);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Carne', 'de cerdo', 70, 100, False, 7, 3);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Pollo', 'de pollo', 70, 100, False, 7, 3);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Pavo', 'de pavo', 70, 100, False, 7, 3);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Pescado', 'de pescado', 70, 100, False, 7, 3);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Huevos', 'de gallina', 20, 100, False, 1, 3);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Huevos', 'de codorniz', 20, 100, False, 1, 3);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Agua', 'Salvavidas', 10, 100, False, 1, 3);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Agua', 'Cielo', 10, 100, False, 1, 3);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Agua', 'Dasani', 10, 100, True, 1, 3);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Comida para Perro', 'Chihuahua', 50, 100, True, 1, 3);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Comida para Perro', 'Dog Chow', 50, 100, False, 1, 3);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Comida para Perro', 'Pedigree', 50, 100, True, 1, 3);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Comida para Perro', 'Purina', 50, 100, True, 1, 3);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Salmon', 'De lata', 50, 100, True, 1, 3);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Salmon', 'Fresco', 50, 100, False, 1, 3);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Salmon', 'Ahumado', 50, 100, True, 1, 3);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Atun', 'De lata', 50, 100, False, 1, 3);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Atun', 'Fresco', 50, 100, False, 1, 3);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Dulce', 'Bom Bom', 1, 100, False, 1, 3);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Dulce', 'Chiclets Adams', 1, 100, False, 1, 3);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Dulce', 'Chiclets Trident', 1, 100, False, 1, 3);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Dulce', 'Gomitas', 2, 100, False, 1, 3);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Coca-Cola', 'Coca-Cola', 10, 100, False, 1, 3);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Pepsi', 'Pepsi', 10, 100, False, 1, 3);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Fanta', 'Coca-Cola', 10, 100, False, 1, 3);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Sprite', 'Coca-Cola', 10, 100, False, 1, 3);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('7up', 'Pepsi', 10, 100, False, 1, 3);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Fresca', 'Coca-Cola', 10, 100, False, 1, 3);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Mirinda', 'Pepsi', 10, 100, False, 1, 3);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Coca-Cola Light', 'Coca-Cola', 10, 100, False, 1, 3);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Pepsi Light', 'Pepsi', 10, 100, False, 1, 3);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Fanta Light', 'Coca-Cola', 10, 100, False, 1, 3);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Queso', 'Dos Pinos', 15, 100, False, 3, 3);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Queso', 'Pil', 15, 100, False, 3, 3);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Jabon', 'pilas', 15, 100, False, 4, 3);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Jabon', 'Dove', 15, 100, False, 4, 3);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Jabon', 'Palmolive', 15, 100, False, 4, 3);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Shampoo', 'Sedal', 15, 100, False, 4, 3);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Shampoo', 'Pantene', 15, 100, False, 4, 3);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Shampoo', 'Head & Shoulders', 15, 100, True, 4, 3);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Shampoo', 'Dove', 15, 100, True, 4, 3);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Crema', 'Nivea', 15, 100, True, 4, 3);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Crema', 'Ponds', 15, 100, True, 4, 3);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Crema', 'Dove', 15, 100, True, 4, 3);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Crema', 'Palmolive', 15, 100, True, 4, 3);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Papel Higienico', 'Scott', 15, 100, True, 5, 3);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Papel Higienico', 'Suavel', 15, 100, True, 5, 3);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Leche', 'Dos Pinos', 12, 100, False, 3, 3);
INSERT INTO ControlEmpresas.Producto(nombreProducto, fabricante, precio, cantidad, estado, pasillo, idTienda) VALUES ('Leche', 'Alpura', 12, 100, False, 3, 3);

/*SUCURSAL 1 EMPLEADOS*/

INSERT INTO ControlPersonal.Empleado(nombreEmpleado, telefono, rol, dpi, cajas, username, password, idTienda) VALUES ('Emilio', '12345678', 'Administrador', '1234567891011',NULL, 'emilio', '123456', 1);
INSERT INTO ControlPersonal.Empleado(nombreEmpleado, telefono, rol, dpi, cajas, username, password, idTienda) VALUES ('Juan', '12345678', 'Cajero', '1234567891011',1 , 'juan', '123456', 1);
INSERT INTO ControlPersonal.Empleado(nombreEmpleado, telefono, rol, dpi, cajas, username, password, idTienda) VALUES ('Ramiro', '12345678', 'Cajero', '1234567891011', 2 ,'ramiro', '123456', 1);
INSERT INTO ControlPersonal.Empleado(nombreEmpleado, telefono, rol, dpi, cajas, username, password, idTienda) VALUES ('Miguel', '12345678', 'Cajero', '1234567891011',3 , 'migue', '123456', 1);
INSERT INTO ControlPersonal.Empleado(nombreEmpleado, telefono, rol, dpi, cajas, username, password, idTienda) VALUES ('Toto', '12345678', 'Cajero', '1234567891011', 4 ,'toto', '123456', 1);
INSERT INTO ControlPersonal.Empleado(nombreEmpleado, telefono, rol, dpi, cajas, username, password, idTienda) VALUES ('Micky', '12345678', 'Cajero', '1234567891011',5 , 'micky', '123456', 1);
INSERT INTO ControlPersonal.Empleado(nombreEmpleado, telefono, rol, dpi, cajas, username, password, idTienda) VALUES ('Sebas', '12345678', 'Cajero', '1234567891011',6 , 'sebas', '123456', 1);
INSERT INTO ControlPersonal.Empleado(nombreEmpleado, telefono, rol, dpi, cajas, username, password, idTienda) VALUES ('Pedro', '12345678', 'Bodega', '1234567891011', NULL ,'pedro', '123456', 1);
INSERT INTO ControlPersonal.Empleado(nombreEmpleado, telefono, rol, dpi, cajas, username, password, idTienda) VALUES ('Maria', '12345678', 'Inventario', '1234567891011',NULL , 'maria', '123456', 1);
INSERT INTO ControlPersonal.Empleado(nombreEmpleado, telefono, rol, dpi, cajas, username, password, idTienda) VALUES ('Jose', '12345678', 'Inventario', '1234567891011', NULL ,'jose', '123456', 1);
INSERT INTO ControlPersonal.Empleado(nombreEmpleado, telefono, rol, dpi, cajas, username, password, idTienda) VALUES ('Luis', '12345678', 'Inventario', '1234567891011', NULL ,'luis', '123456', 1);
INSERT INTO ControlPersonal.Empleado(nombreEmpleado, telefono, rol, dpi, cajas, username, password, idTienda) VALUES ('Carlos', '12345678', 'Inventario', '1234567891011', NULL ,'carlos', '123456', 1);

/*SUCURSAL 2 EMPLEADOS*/
INSERT INTO ControlPersonal.Empleado(nombreEmpleado, telefono, rol, dpi, cajas, username, password, idTienda) VALUES ('Ale', '12345678', 'Administrador', '1234567891011',NULL , 'ale', '123456', 2);
INSERT INTO ControlPersonal.Empleado(nombreEmpleado, telefono, rol, dpi, cajas, username, password, idTienda) VALUES ('Ericka', '12345678', 'Cajero', '1234567891011',1 , 'ericka', '123456', 2);
INSERT INTO ControlPersonal.Empleado(nombreEmpleado, telefono, rol, dpi, cajas, username, password, idTienda) VALUES ('Erick', '12345678', 'Cajero', '1234567891011', 2 ,'erick', '123456', 2);
INSERT INTO ControlPersonal.Empleado(nombreEmpleado, telefono, rol, dpi, cajas, username, password, idTienda) VALUES ('Lupita', '12345678', 'Cajero', '1234567891011', 3 ,'lupita', '123456', 2);
INSERT INTO ControlPersonal.Empleado(nombreEmpleado, telefono, rol, dpi, cajas, username, password, idTienda) VALUES ('Veronica', '12345678', 'Cajero', '1234567891011',4 , 'vero', '123456', 2);
INSERT INTO ControlPersonal.Empleado(nombreEmpleado, telefono, rol, dpi, cajas, username, password, idTienda) VALUES ('Alan', '12345678', 'Cajero', '1234567891011', 5 ,'alan', '123456', 2);
INSERT INTO ControlPersonal.Empleado(nombreEmpleado, telefono, rol, dpi, cajas, username, password, idTienda) VALUES ('Raul', '12345678', 'Cajero', '1234567891011', 6 ,'raul', '123456', 2);
INSERT INTO ControlPersonal.Empleado(nombreEmpleado, telefono, rol, dpi, cajas, username, password, idTienda) VALUES ('Ariel', '12345678', 'Bodega', '1234567891011', NULL ,'ariel', '123456', 2);
INSERT INTO ControlPersonal.Empleado(nombreEmpleado, telefono, rol, dpi, cajas, username, password, idTienda) VALUES ('Bety', '12345678', 'Inventario', '1234567891011', NULL ,'bety', '123456', 2);
INSERT INTO ControlPersonal.Empleado(nombreEmpleado, telefono, rol, dpi, cajas, username, password, idTienda) VALUES ('Marco', '12345678', 'Inventario', '1234567891011', NULL ,'marco', '123456', 2);
INSERT INTO ControlPersonal.Empleado(nombreEmpleado, telefono, rol, dpi, cajas, username, password, idTienda) VALUES ('Elba', '12345678', 'Inventario', '1234567891011', NULL ,'elba', '123456', 2);
INSERT INTO ControlPersonal.Empleado(nombreEmpleado, telefono, rol, dpi, cajas, username, password, idTienda) VALUES ('Juan', '12345678', 'Inventario', '1234567891011', NULL ,'juan', '123456', 2);

/*SUCURSAL 3 EMPLEADOS*/
INSERT INTO ControlPersonal.Empleado(nombreEmpleado, telefono, rol, dpi, cajas, username, password, idTienda) VALUES ('Diego', '12345678', 'Administrador', '1234567891011',NULL , 'diego', '123456', 3);
INSERT INTO ControlPersonal.Empleado(nombreEmpleado, telefono, rol, dpi, cajas, username, password, idTienda) VALUES ('Rodrigo', '12345678', 'Cajero', '1234567891011',1 , 'rodrigo', '123456', 3);
INSERT INTO ControlPersonal.Empleado(nombreEmpleado, telefono, rol, dpi, cajas, username, password, idTienda) VALUES ('Lia', '12345678', 'Cajero', '1234567891011', 2 ,'lia', '123456', 3);
INSERT INTO ControlPersonal.Empleado(nombreEmpleado, telefono, rol, dpi, cajas, username, password, idTienda) VALUES ('Dolly', '12345678', 'Cajero', '1234567891011', 3 ,'dolly', '123456', 3);
INSERT INTO ControlPersonal.Empleado(nombreEmpleado, telefono, rol, dpi, cajas, username, password, idTienda) VALUES ('Valeria', '12345678', 'Cajero', '1234567891011',4 , 'vale', '123456', 3);
INSERT INTO ControlPersonal.Empleado(nombreEmpleado, telefono, rol, dpi, cajas, username, password, idTienda) VALUES ('Abdo', '12345678', 'Cajero', '1234567891011', 5 ,'abdo', '123456', 3);
INSERT INTO ControlPersonal.Empleado(nombreEmpleado, telefono, rol, dpi, cajas, username, password, idTienda) VALUES ('Fernando', '12345678', 'Cajero', '1234567891011',6 , 'fernando', '123456', 3);
INSERT INTO ControlPersonal.Empleado(nombreEmpleado, telefono, rol, dpi, cajas, username, password, idTienda) VALUES ('Levi', '12345678', 'Bodega', '1234567891011',NULL , 'levi', '123456', 3);
INSERT INTO ControlPersonal.Empleado(nombreEmpleado, telefono, rol, dpi, cajas, username, password, idTienda) VALUES ('Daniel', '12345678', 'Inventario', '1234567891011',NULL , 'dani', '123456', 3);
INSERT INTO ControlPersonal.Empleado(nombreEmpleado, telefono, rol, dpi, cajas, username, password, idTienda) VALUES ('Julian', '12345678', 'Inventario', '1234567891011', NULL ,'julian', '123456', 3);
INSERT INTO ControlPersonal.Empleado(nombreEmpleado, telefono, rol, dpi, cajas, username, password, idTienda) VALUES ('Ricardo', '12345678', 'Inventario', '1234567891011', NULL ,'ricardo', '123456', 3);
INSERT INTO ControlPersonal.Empleado(nombreEmpleado, telefono, rol, dpi, cajas, username, password, idTienda) VALUES ('Mauricio', '12345678', 'Inventario', '1234567891011', NULL ,'mau', '123456', 3);

/*CLIENTE 0*/
INSERT INTO ControlPersonal.Cliente(nitCliente, nombreCliente, telefono, dpi, tarjeta, puntos, descuento, direccion) VALUES ('CF', 'CF', '0000', '0000', '0000', 0, 0, 'CF');